import React, { useState } from "react";
import { Pencil, Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";
import type { FinancialCategory } from "@/hooks/useFinancialTransactions";

interface Props { open: boolean; onOpenChange: (open: boolean) => void; categories: FinancialCategory[]; }

const CategoryManager: React.FC<Props> = ({ open, onOpenChange, categories }) => {
  const queryClient = useQueryClient();
  const [name, setName] = useState("");
  const [kind, setKind] = useState<"entrada" | "saida" | "ambos">("entrada");
  const [editingId, setEditingId] = useState<string | null>(null);
  const [editingName, setEditingName] = useState("");
  const invalidate = () => { queryClient.invalidateQueries({ queryKey: ["financial-categories-all"] }); queryClient.invalidateQueries({ queryKey: ["financial-categories-active"] }); };
  const createMutation = useMutation({ mutationFn: async () => { if (!name.trim()) throw new Error("Informe o nome da categoria."); const user = await supabase.auth.getUser(); const { error } = await supabase.from("financial_categories").insert({ name: name.trim(), kind, created_by: user.data.user?.id }); if (error) throw error; }, onSuccess: () => { invalidate(); setName(""); toast.success("Categoria criada."); }, onError: (error: Error) => toast.error(error.message.includes("duplicate") ? "Essa categoria já existe para este tipo." : error.message) });
  const updateMutation = useMutation({ mutationFn: async ({ id, value }: { id: string; value: string }) => { if (!value.trim()) throw new Error("Informe um nome válido."); const { error } = await supabase.from("financial_categories").update({ name: value.trim() }).eq("id", id); if (error) throw error; }, onSuccess: () => { invalidate(); setEditingId(null); toast.success("Categoria atualizada."); }, onError: (error: Error) => toast.error(error.message.includes("duplicate") ? "Essa categoria já existe para este tipo." : error.message) });
  const toggleMutation = useMutation({ mutationFn: async (category: FinancialCategory) => { const { error } = await supabase.from("financial_categories").update({ active: !category.active }).eq("id", category.id); if (error) throw error; }, onSuccess: invalidate, onError: () => toast.error("Não foi possível atualizar a categoria.") });
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="sm:max-w-[620px]"><DialogHeader><DialogTitle>Gerenciar categorias</DialogTitle></DialogHeader><div className="space-y-5 py-2"><div><p className="text-sm text-slate-500">Crie, renomeie ou ative e desative categorias financeiras.</p><div className="grid grid-cols-1 sm:grid-cols-[1fr_150px_auto] gap-3 items-end mt-4"><div className="space-y-2"><Label>Nova categoria</Label><Input value={name} onChange={(event) => setName(event.target.value)} placeholder="Ex.: Serviços" /></div><div className="space-y-2"><Label>Aplicável a</Label><Select value={kind} onValueChange={(value: "entrada" | "saida" | "ambos") => setKind(value)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="entrada">Entradas</SelectItem><SelectItem value="saida">Saídas</SelectItem><SelectItem value="ambos">Ambos</SelectItem></SelectContent></Select></div><Button onClick={() => createMutation.mutate()} disabled={createMutation.isPending}><Plus className="mr-2 size-4" />Adicionar</Button></div></div><div className="max-h-72 overflow-y-auto rounded-lg border border-slate-200 divide-y divide-slate-100">{categories.map((category) => <div key={category.id} className="flex items-center justify-between gap-3 px-4 py-3"><div className="min-w-0 flex-1">{editingId === category.id ? <div className="flex gap-2"><Input autoFocus value={editingName} onChange={(event) => setEditingName(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") updateMutation.mutate({ id: category.id, value: editingName }); }} /><Button size="sm" onClick={() => updateMutation.mutate({ id: category.id, value: editingName })}>Salvar</Button><Button size="sm" variant="ghost" onClick={() => setEditingId(null)}>Cancelar</Button></div> : <><p className="font-medium text-slate-800">{category.name}</p><p className="text-xs text-slate-400">{category.kind === "ambos" ? "Entrada e saída" : category.kind === "entrada" ? "Entrada" : "Saída"}</p></>}</div>{editingId !== category.id && <div className="flex items-center gap-3"><button aria-label={`Renomear ${category.name}`} onClick={() => { setEditingId(category.id); setEditingName(category.name); }} className="text-slate-500 hover:text-blue-600"><Pencil className="size-4" /></button><div className="flex items-center gap-2"><Switch checked={category.active} onCheckedChange={() => toggleMutation.mutate(category)} /><span className="text-xs text-slate-500">{category.active ? "Ativa" : "Inativa"}</span></div></div>}</div>)}{categories.length === 0 && <p className="p-5 text-center text-sm text-slate-500">Nenhuma categoria cadastrada.</p>}</div></div><DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>Fechar</Button></DialogFooter></DialogContent></Dialog>;
};
export default CategoryManager;
