
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://syzhrxnnoncaftojlflv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_NC8eCOvvVmGCsy9f0wQ3Cg_KZlPdJlw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
