import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Loader2, Mail, Receipt } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { formatCurrency } from "@/utils/formatters";
import CollectInvoicesModal from "@/components/admin/companies/CollectInvoicesModal";

type PendingInvoice = { id: string; amount: number; due_date: string; description: string | null; company: { id: string; name: string; email: string | null; accounting_email: string | null; cnpj: string | null } | null };

const PendingInvoicesModal: React.FC<{ open: boolean; onOpenChange: (open: boolean) => void }> = ({ open, onOpenChange }) => {
  const navigate = useNavigate();
  const [selectedCompany, setSelectedCompany] = useState<PendingInvoice["company"]>(null);
  const { data: invoices = [], isLoading } = useQuery({ queryKey: ["dashboard-pending-invoices"], queryFn: async () => { const { data, error } = await supabase.from("invoices").select("id, amount, due_date, description, company:companies(id, name, email, accounting_email, cnpj)").eq("status", "Pendente").order("due_date", { ascending: true }); if (error) throw error; return (data ?? []) as unknown as PendingInvoice[]; }, enabled: open });
  const grouped = Array.from(invoices.reduce((map, invoice) => { if (!invoice.company) return map; const current = map.get(invoice.company.id) || { company: invoice.company, invoices: [] as PendingInvoice[] }; current.invoices.push(invoice); map.set(invoice.company.id, current); return map; }, new Map<string, { company: NonNullable<PendingInvoice["company"]>; invoices: PendingInvoice[] }>()).values());
  return <><Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="sm:max-w-[760px]"><DialogHeader><DialogTitle className="flex items-center gap-2"><Receipt className="size-5 text-amber-600" />Empresas com faturas a receber</DialogTitle></DialogHeader><div className="max-h-[55vh] overflow-y-auto rounded-lg border border-slate-200"><table className="w-full text-left"><thead className="sticky top-0 bg-slate-50 border-b border-slate-200"><tr><th className="p-3 text-xs uppercase text-slate-500">Empresa</th><th className="p-3 text-xs uppercase text-slate-500">Faturas</th><th className="p-3 text-xs uppercase text-slate-500">Total</th><th className="p-3 text-xs uppercase text-slate-500 text-right">Ação</th></tr></thead><tbody className="divide-y divide-slate-100">{isLoading ? <tr><td colSpan={4} className="p-8 text-center"><Loader2 className="mx-auto size-6 animate-spin text-blue-600" /></td></tr> : grouped.map(({ company, invoices: companyInvoices }) => <tr key={company.id} onClick={() => { onOpenChange(false); navigate("/admin/empresas", { state: { companyId: company.id } }); }} className="cursor-pointer hover:bg-slate-50"><td className="p-3"><div className="text-left"><p className="font-semibold text-blue-700 hover:underline">{company.name}</p><p className="text-xs text-slate-500">{company.cnpj || "CNPJ não informado"}</p></div></td><td className="p-3 text-sm text-slate-600">{companyInvoices.length}</td><td className="p-3 text-sm font-bold text-red-600">{formatCurrency(companyInvoices.reduce((sum, invoice) => sum + Number(invoice.amount), 0))}</td><td className="p-3 text-right"><Button size="sm" onClick={(event) => { event.stopPropagation(); setSelectedCompany(company); }}><Mail className="mr-2 size-4" />Cobrar</Button></td></tr>)}{!isLoading && grouped.length === 0 && <tr><td colSpan={4} className="p-8 text-center text-sm text-slate-500">Nenhuma fatura pendente encontrada.</td></tr>}</tbody></table></div></DialogContent></Dialog><CollectInvoicesModal isOpen={!!selectedCompany} onClose={() => setSelectedCompany(null)} companyId={selectedCompany?.id || ""} companyName={selectedCompany?.name || ""} companyEmail={selectedCompany?.email || ""} accountingEmail={selectedCompany?.accounting_email || ""} companyCnpj={selectedCompany?.cnpj || ""} /></>;
};
export default PendingInvoicesModal;
